version: '3'
services:
  db:
    image: mongo
    container_name: my_mongo_db
    ports: 
      - "27017:27017"
    
  webapp:
    build: note-app
    image: web_app
    container_name: my_web_app
    volumes:
      - ./note-app:/usr/src/app
    ports:
      - "6001:5000"
    depends_on:
      - db
    stdin_open: true 
    tty: true
