name: note-App-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv sync --dev --python $(which python)
        pipenv shell --fancy --python $(which python)

    - name: Test with pytest (note-app)
      run: |
        cd note-app
        pipenv run coverage run -m pytest
        pipenv run coverage report --fail-under=80